package simulator

import (
	"context"
	"strings"
	"testing"
	"time"

	corev1 "k8s.io/api/core/v1"

	"github.com/mdryaaan/kubelens/internal/detector"
	"github.com/mdryaaan/kubelens/internal/watcher"
)

var simClock = time.Date(2026, 8, 20, 12, 0, 0, 0, time.UTC)

func newTestSimulator(seed int64) *Simulator {
	return New(Options{Seed: seed, Interval: time.Millisecond, Now: func() time.Time { return simClock }})
}

// A demo that produces different pods each run is a demo nobody can rehearse.
func TestSameSeedProducesTheSameCluster(t *testing.T) {
	a := newTestSimulator(42)
	b := newTestSimulator(42)

	if a.Cluster().PodCount() != b.Cluster().PodCount() {
		t.Fatalf("pod counts differ: %d vs %d", a.Cluster().PodCount(), b.Cluster().PodCount())
	}
	for i := range a.Cluster().Pods {
		left, right := a.Cluster().Pods[i], b.Cluster().Pods[i]
		if left.Name != right.Name || left.Namespace != right.Namespace {
			t.Fatalf("pod %d differs: %s/%s vs %s/%s",
				i, left.Namespace, left.Name, right.Namespace, right.Name)
		}
		if left.Spec.NodeName != right.Spec.NodeName {
			t.Errorf("pod %s was scheduled differently: %s vs %s",
				left.Name, left.Spec.NodeName, right.Spec.NodeName)
		}
	}

	// And the failures must land in the same order too.
	for i := 0; i < 4; i++ {
		leftEvents := a.InjectNext()
		rightEvents := b.InjectNext()
		if len(leftEvents) != len(rightEvents) {
			t.Fatalf("injection %d produced different event counts", i)
		}
		for j := range leftEvents {
			if leftEvents[j].Name != rightEvents[j].Name {
				t.Errorf("injection %d event %d hit different pods: %s vs %s",
					i, j, leftEvents[j].Name, rightEvents[j].Name)
			}
		}
	}
}

func TestDifferentSeedsProduceDifferentClusters(t *testing.T) {
	a := newTestSimulator(1)
	b := newTestSimulator(2)

	same := 0
	for i := range a.Cluster().Pods {
		if a.Cluster().Pods[i].Name == b.Cluster().Pods[i].Name {
			same++
		}
	}
	if same == len(a.Cluster().Pods) {
		t.Error("two different seeds produced identical pod names")
	}
}

func TestSeededClusterLooksReal(t *testing.T) {
	cluster := newTestSimulator(7).Cluster()

	if cluster.PodCount() < 10 {
		t.Errorf("cluster has only %d pods", cluster.PodCount())
	}
	if len(cluster.Deployments) != len(workloads) {
		t.Errorf("got %d deployments, want %d", len(cluster.Deployments), len(workloads))
	}

	namespaces := map[string]bool{}
	for _, pod := range cluster.Pods {
		namespaces[pod.Namespace] = true

		// Pod names follow the real deployment-hash-suffix shape.
		if strings.Count(pod.Name, "-") < 2 {
			t.Errorf("pod name %q does not look generated by a ReplicaSet", pod.Name)
		}
		if pod.Spec.NodeName == "" {
			t.Errorf("pod %s was never scheduled", pod.Name)
		}
		if len(pod.Spec.Containers) == 0 {
			t.Fatalf("pod %s has no containers", pod.Name)
		}
		// Limits are what make OOM incidents explainable.
		if pod.Spec.Containers[0].Resources.Limits.Memory().IsZero() {
			t.Errorf("pod %s has no memory limit", pod.Name)
		}
	}
	if len(namespaces) < 3 {
		t.Errorf("cluster spans only %d namespaces", len(namespaces))
	}

	// Nothing is broken before an injection.
	if cluster.Unhealthy() != 0 {
		t.Errorf("%d pods were unhealthy in a freshly seeded cluster", cluster.Unhealthy())
	}
}

// The injectors edit the real objects, so the real detector rules have to fire
// on them. If this test fails, the demo is showing something the product would
// not actually detect.
func TestInjectedFailuresAreDetectedByTheRealRules(t *testing.T) {
	for _, category := range injectionOrder {
		t.Run(string(category), func(t *testing.T) {
			sim := New(Options{
				Seed: 99, Interval: time.Millisecond,
				Now:        func() time.Time { return simClock },
				Categories: []detector.Category{category},
			})

			engine := detector.NewEngine(detector.Options{
				Now: func() time.Time { return simClock },
			})

			var found []detector.Incident
			for _, event := range sim.InjectNext() {
				found = append(found, engine.Process(event)...)
			}

			if len(found) == 0 {
				t.Fatalf("injecting %s produced no detected incident", category)
			}
			if found[0].Category != category {
				t.Errorf("injected %s but detected %s", category, found[0].Category)
			}
		})
	}
}

// The evidence has to be the kind of text a real container emits, or the
// explanation engine is being fed fiction.
func TestInjectedIncidentsCarryPlausibleEvidence(t *testing.T) {
	tests := map[detector.Category][]string{
		detector.OOMKilled:        {"OutOfMemoryError", "heap", "MemoryError", "out of memory"},
		detector.CrashLoopBackOff: {"Traceback", "panic:", "Error:", "Exception"},
	}

	for category, wanted := range tests {
		t.Run(string(category), func(t *testing.T) {
			sim := New(Options{
				Seed: 5, Now: func() time.Time { return simClock },
				Categories: []detector.Category{category},
			})
			events := sim.InjectNext()
			if len(events) == 0 {
				t.Fatal("nothing was injected")
			}

			pod := events[0].Pod
			if pod == nil {
				t.Fatal("no pod on the event")
			}
			w, _ := sim.Cluster().Workload(pod.Name)

			lines, err := sim.Logs().Fetch(context.Background(), pod.Namespace, pod.Name, w.container, 100)
			if err != nil {
				t.Fatalf("no logs were recorded: %v", err)
			}

			joined := strings.Join(lines, "\n")
			matched := false
			for _, want := range wanted {
				if strings.Contains(joined, want) {
					matched = true
					break
				}
			}
			if !matched {
				t.Errorf("logs contain none of %v:\n%s", wanted, joined)
			}
			// A failing log among only failure lines is not what anyone reads.
			if len(lines) < 5 {
				t.Errorf("only %d log lines were generated; the failure has no context", len(lines))
			}
		})
	}
}

func TestImagePullIncidentRecordsEventsWithoutLogs(t *testing.T) {
	sim := New(Options{
		Seed: 11, Now: func() time.Time { return simClock },
		Categories: []detector.Category{detector.ImagePullBackOff},
	})

	events := sim.InjectNext()
	if len(events) == 0 {
		t.Fatal("nothing was injected")
	}
	pod := events[0].Pod

	// A container that never started has no output — the events carry the story.
	records, err := sim.Events().Recent(context.Background(), pod.Namespace, "pod/"+pod.Name, 10)
	if err != nil {
		t.Fatalf("no events were recorded: %v", err)
	}
	if len(records) < 2 {
		t.Errorf("got %d events, want the pull sequence", len(records))
	}

	joined := ""
	for _, record := range records {
		joined += record.Message + "\n"
	}
	if !strings.Contains(joined, "manifest unknown") {
		t.Errorf("events do not carry a real registry error:\n%s", joined)
	}
}

// A demo left running must not end with every pod broken and nothing to show.
func TestSimulatorHealsWhenNothingIsLeftToBreak(t *testing.T) {
	sim := New(Options{
		Seed: 3, Now: func() time.Time { return simClock },
		Categories: []detector.Category{detector.ProbeFailure},
	})

	for i := 0; i < 200; i++ {
		sim.InjectNext()
	}

	if sim.Cluster().Unhealthy() == sim.Cluster().PodCount() {
		t.Error("every pod ended up broken with no recovery")
	}
}

// Demo mode and cluster mode must run through the same pipeline.
func TestSimulatorImplementsWatchSource(t *testing.T) {
	var source watcher.Source = newTestSimulator(1)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	out := make(chan watcher.WatchEvent, 256)
	done := make(chan struct{})
	go func() {
		defer close(done)
		_ = source.Run(ctx, out)
	}()

	// The initial cluster is streamed before anything breaks, so the dashboard
	// is populated immediately.
	var pods, deployments int
	timeout := time.After(2 * time.Second)
	for pods+deployments < 10 {
		select {
		case event := <-out:
			switch event.Kind {
			case watcher.KindPod:
				pods++
			case watcher.KindDeployment:
				deployments++
			}
		case <-timeout:
			t.Fatalf("only saw %d pods and %d deployments", pods, deployments)
		}
	}

	cancel()
	<-done
}

func TestSnapshotCountsTheCluster(t *testing.T) {
	sim := newTestSimulator(21)

	before := sim.Snapshot()
	if before.TotalPods == 0 || before.Nodes == 0 || before.Deployments == 0 {
		t.Fatalf("empty snapshot: %+v", before)
	}
	if before.UnhealthyPods != 0 {
		t.Errorf("a fresh cluster reported %d unhealthy pods", before.UnhealthyPods)
	}

	sim.InjectNext()
	if after := sim.Snapshot(); after.UnhealthyPods == 0 {
		t.Error("an injected failure did not show up in the snapshot")
	}
}

func TestPickPodSkipsAlreadyBrokenPods(t *testing.T) {
	sim := newTestSimulator(13)
	cluster := sim.Cluster()

	// Break everything, then confirm no injector claims a candidate.
	for _, pod := range cluster.Pods {
		pod.Status.Phase = corev1.PodPending
	}

	if got := pickPod(sim.rng, cluster, func(workload) bool { return true }); got != nil {
		t.Errorf("picked an already-broken pod: %s", got.Name)
	}
}

// A pod that never scheduled, or whose image never pulled, has written nothing.
// Leaving earlier output in place would hand the explanation engine evidence
// that does not exist.
func TestFailuresWithNoOutputClearTheLog(t *testing.T) {
	for _, category := range []detector.Category{detector.PendingTimeout, detector.ImagePullBackOff} {
		t.Run(string(category), func(t *testing.T) {
			sim := New(Options{
				Seed: 17, Now: func() time.Time { return simClock },
				Categories: []detector.Category{category},
			})

			events := sim.InjectNext()
			if len(events) == 0 {
				t.Fatal("nothing was injected")
			}
			pod := events[0].Pod
			w, _ := sim.Cluster().Workload(pod.Name)

			lines, err := sim.Logs().Fetch(context.Background(), pod.Namespace, pod.Name, w.container, 50)
			if err == nil && len(lines) > 0 {
				t.Errorf("a container that never ran still has %d log lines:\n%s",
					len(lines), strings.Join(lines, "\n"))
			}
		})
	}
}

// A cluster where everything is failing tells a viewer nothing about which
// failure matters, so the simulator recovers workloads once it degrades past a
// legible fraction.
func TestSimulatorKeepsTheClusterMostlyHealthy(t *testing.T) {
	sim := New(Options{Seed: 8, Now: func() time.Time { return simClock }})

	worst := 0.0
	for i := 0; i < 300; i++ {
		sim.InjectNext()

		ratio := float64(sim.Cluster().Unhealthy()) / float64(sim.Cluster().PodCount())
		if ratio > worst {
			worst = ratio
		}
	}

	// The threshold is the trigger, not a hard cap — one more failure can land
	// before recovery kicks in — so a little headroom is expected.
	if worst > maxUnhealthyRatio+0.2 {
		t.Errorf("the cluster degraded to %.0f%% unhealthy, past the %.0f%% target",
			worst*100, maxUnhealthyRatio*100)
	}
	if sim.Cluster().Unhealthy() == 0 {
		t.Error("nothing is broken after 300 injections; the demo would be empty")
	}
}

// Recovery has to produce watch events, or the dashboard shows a cluster that
// never gets better.
func TestRecoveryEmitsEvents(t *testing.T) {
	sim := New(Options{Seed: 4, Now: func() time.Time { return simClock }})

	for i := 0; i < 200; i++ {
		sim.InjectNext()
	}

	before := sim.Cluster().Unhealthy()
	var recovered bool
	for i := 0; i < 20 && !recovered; i++ {
		if events := sim.InjectNext(); len(events) > 0 && sim.Cluster().Unhealthy() < before {
			recovered = true
		}
		before = sim.Cluster().Unhealthy()
	}

	if !recovered {
		t.Error("the unhealthy count never went down")
	}
}

// A container that crashed six times and then stabilised still restarted six
// times; erasing that would remove history the dashboard legitimately shows.
func TestRecoveryKeepsTheRestartCount(t *testing.T) {
	sim := New(Options{
		Seed: 6, Now: func() time.Time { return simClock },
		Categories: []detector.Category{detector.CrashLoopBackOff},
	})

	events := sim.InjectNext()
	if len(events) == 0 {
		t.Fatal("nothing was injected")
	}
	pod := sim.Cluster().Pod(events[0].Name)
	restarts := pod.Status.ContainerStatuses[0].RestartCount
	if restarts == 0 {
		t.Fatal("the injected crash loop recorded no restarts")
	}

	w, _ := sim.Cluster().Workload(pod.Name)
	healPod(pod, w, simClock)

	if got := pod.Status.ContainerStatuses[0].RestartCount; got != restarts {
		t.Errorf("restart count = %d after recovery, want it preserved at %d", got, restarts)
	}
	if podIsBroken(pod) {
		t.Error("the pod is still reported as broken after recovery")
	}
}
